apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-fiis-deployment
  labels:
    version: "buildNumber"
    app: calcFiis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calcFiis
  template:
    metadata:
      labels:
        app: calcFiis
    spec:
      containers:
      - name: calculadora-fiis
        image: joaoallmeida/calculadora-fiis:latest
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: calculadora-fiis-service
spec:
  selector:
    app.kubernetes.io/name: calcFiis
  type: LoadBalancer
  ports:
  - name: http 
    protocol: TCP
    port: 5000
    targetPort: 5000
  externalIPs:
    - myIp