apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-fiis-deployment
  labels:
    version: buildNumber
    app: calcFiis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calcFiis
  template:
    metadata:
      labels:
        app: calcFiis
    spec:
      containers:
      - name: calculadora-fiis
        image: joaoallmeida/calculadora-fiis:latest
        ports:
        - containerPort: 5000